
HIGHER_IN_DC_THAN_MONOCYTE_THRESH = -7.5
HIGHER_IN_ENDOTHEL_THAN_ALL_EXCEPT_UNKNOWN_THRESH = -7
STRONG_C_MONOCYTE_SPECIFIC_THRESH = -8
STRONG_C_MONOCYTE_SPECIFIC_C_DC2_THRESH = -7
HIGHER_IN_NC_MONOCYTE_THAN_C_MONOCYTE_THRESH = -7.5
HIGHER_IN_INTERM_MONOCYTE_THAN_C_MONOCYTE_THRESH = -8
HIGHER_IN_C_DC2_THAN_INTERM_MONOCYTE_THRESH = -8
HIGHER_IN_C_DC2_THAN_ALL_HSPCS_THRESH = -7
HIGHER_IN_INTERM_MONOCYTE_THAN_C_DC2_THRESH = -7.8
C_INTERMEDIATE_NC_MONOCYTE_SOMEWHAT_SPECIFIC_THRESH = -7
C_INTERMEDIATE_NC_MONOCYTE_SOMEWHAT_SPECIFIC_C_DC2_THRESH = -6.7
HIGHER_IN_C_DC1_THAN_AS_DC_AND_C_DC2_THRESH = -7.7
HIGHER_IN_MONOCYTE_THAN_C_DC1_THRESH = -7.6
HIGHER_IN_B_THAN_MONOCYTES_AND_NC_MONOCYTES_THRESH = -8.2
NC_MONOCYTE_SPECIFIC_THRESH = -8
LAMP3_OUTLIER_SPECIFIC_THRESH = -7.7
HIGHER_IN_NC_MONOCYTE_THAN_NKT_THRESH = -8
NKT_SOMEWHAT_SPECIFIC_THRESH = -6
HIGHER_IN_DC_THAN_ALL_HSPCS_THRESH = -6.7
HIGHER_IN_P_AND_AS_DC_THAN_MONOCYTE_THRESH = -7.3
HIGHER_IN_C_DC_THAN_MONOCYTE_THRESH = -7.2
HIGHER_IN_DC_THAN_NKT_THRESH = -5
HIGHER_IN_AS_DC_THAN_P_DC_THRESH = -7.4
HIGHER_IN_AS_DC_THAN_C_DC2_THRESH = -8
HIGHER_IN_B_THAN_NKT_THRESH = -6.1
HIGHER_IN_NKT_THAN_NKTDP_THRESH = -7.1
HIGHER_IN_B_THAN_ALL_OTHER_HSPCS_THRESH = -7.6
HIGHER_IN_PRE_B_THAN_ALL_HSPCS_THRESH = -7.5
HIGHER_IN_B_THAN_PRE_B_THRESH = -6
HIGHER_IN_PRE_B_THAN_PRO_B_THRESH = -6
HIGHER_IN_NKTDP_THAN_ALL_MYELOID_HSPCS_THRESH = -7.5
HIGHER_IN_NKTDP_THAN_CLP_THRESH = -7.1
HIGHER_IN_NKTDP_THAN_GMP_L_THRESH = -7.8
HIGHER_IN_NKTDP_THAN_BEMP_THRESH = -6.5
HIGHER_IN_BEMP_THAN_CLP_M_AND_NKTDP_THRESH = -7.3
HIGHER_IN_BEMP_THAN_MEBEMP_L_AND_ERYP_THRESH = -7.5
HIGHER_IN_BEMP_THAN_EP_THRESH = -7.5
HIGHER_IN_BEMP_THAN_MEBEMP_L_THRESH = -7.5
HIGHER_IN_BEMP_THAN_GMP_L_THRESH = -6.2
HIGHER_IN_EP_THAN_MPP_THRESH = -7
HIGHER_IN_ERYP_THAN_MKP_THRESH = -8.2
HIGHER_IN_ERYP_THAN_GMP_L_THRESH = -8.2
HIGHER_IN_MPP_THAN_EP_THRESH = -6.8 # 240625: changed today from -7.5 
HIGHER_IN_GMP_L_THAN_EP_THRESH = -8
HIGHER_IN_GMP_L_THAN_MPP_THRESH = -7.3
HIGHER_IN_GMP_L_THAN_MEBEMP_L_THRESH = -6
HIGHER_IN_MEBEMP_L_THAN_MPP_THRESH = -6.8
HIGHER_IN_MPP_THAN_MEBEMP_L_THRESH = -7.5
HIGHER_IN_MKP_THAN_EP_THRESH = -7.5
HIGHER_IN_MKP_THAN_MEBEMP_L_THRESH = -6
HIGHER_IN_MKP_THAN_MEBEMP_L_AND_ERYP_THRESH = -6.3
HIGHER_IN_NAIVE_B_THAN_MEMORY_B_THRESH = -8.4
HIGHER_IN_PLASMABLAST_THAN_OTHER_MATURE_B_THRESH = -7
HIGHER_IN_AGED_B_THAN_MEMORY_B_THRESH = -6.8
HIGHER_IN_CCDC88A_HIGH_B_THAN_OTHER_MATURE_B_THRESH = -8.2
HIGHER_IN_GMP_L_THAN_ALL_OTHER_HSPCS_THRESH = -8.5
HIGHER_IN_MONOCYTE_THAN_GMP_L_THRESH = -6.3
HIGHER_IN_CFD_TRYPTASE_GMP_L_THAN_GMP_L_THRESH = -6
HIGHER_IN_GMP_L_THAN_ALL_OTHER_HSPCS_DC_PROG_THRESH = -7
HIGHER_IN_MPP_THAN_MKP_THRESH = -8 # according to healthy atlas
HIGHER_IN_B_THAN_PLASMABLAST_THRESH = -6.7
HIGHER_IN_MONOCYTE_THAN_B_THRESH = -6
HIGHER_IN_B_THAN_MONOCYTE_THRESH = -7
PLASMABLAST_SOMEWHAT_SPECIFIC_THRESH = -6.2
HIGHER_IN_PLASMABLAST_THAN_CLP_THRESH = -8
IGHM_IGHG_PLASMABLAST_IGHA_IGLC_THRESH = -6
IGHM_IGHG_PLASMABLAST_IGHM_IGHG_THRESH = -5.3

HIGHER_IN_MONOCYTES_THAN_C_DC_THRESH = -7.8
HIGHER_IN_C_DC_THAN_MONOCYTES_THRESH = -6
HIGHER_IN_C_DC_THAN_P_DC_THRESH = -7.3
HIGHER_IN_P_DC_THAN_AS_AND_C_DC_THRESH = -6.7
HIGHER_IN_C_DC_THAN_AS_DC_THRESH = -7.8
HIGHER_IN_C_DC_THAN_NC_MONOCYTES_THRESH = -7.5

HIGHER_IN_CLP_M_THAN_ALL_MYELOID_HSPCS_THRESH = -7.1

HIGHER_IN_CLP_M_THAN_ALL_MYELOID_HSPCS_CLP_E_LOW_THRESH = -8 # -7.5 according to sparsity in normal individuals. -8 according to abnormal looking dist in patients.
HIGHER_IN_CLP_M_THAN_ALL_MYELOID_HSPCS_CLP_E_HIGH_THRESH = -7.1

# preserving HSC_MEBEMP_and_later traj
HIGHER_IN_GMP_L_THAN_ALL_OTHER_HSPCS_PRESERVING_HSC_MEBEMP_AND_LATER_TRAJ_THRESH = -9.5

# preserving HSC_GMP traj
HIGHER_IN_MEBEMP_L_THAN_GMP_L_PRESERVING_HSC_GMP_TRAJ_THRESH = -8

# preserving MEBEMP_BEMP traj
HIGHER_IN_GMP_L_THAN_BEMP_PRESERVING_MEBEMP_BEMP_TRAJ_THRESH = -6.8
HIGHER_IN_ERYP_THAN_BEMP_PRESERVING_MEBEMP_BEMP_TRAJ_THRESH = -6.4
HIGHER_IN_MPP_THAN_BEMP_PRESERVING_MEBEMP_BEMP_TRAJ_THRESH = -7.2

# kind of preserving MEBEMP_MKP traj
HIGHER_IN_ERYP_THAN_MKP_AND_MEBEMP_L_PRESERVING_MEBEMP_MKP_TRAJ_THRESH = -8.3
HIGHER_IN_MKP_THAN_MEBEMP_L_AND_ERYP_PRESERVING_MEBEMP_MKP_TRAJ_THRESH = -7.2
HIGHER_IN_MPP_THAN_MKP_PRESERVING_MEBEMP_MKP_TRAJ_THRESH = -8

# preserving MEBEMP_ERYP traj
HIGHER_IN_BEMP_THAN_ERYP_PRESERVING_MEBEMP_ERYP_TRAJ_THRESH = -7.2
# HIGHER_IN_MKP_THAN_ERYP_PRESERVING_MEBEMP_ERYP_TRAJ_THRESH = -7.5
HIGHER_IN_MPP_THAN_ERYP_PRESERVING_MEBEMP_ERYP_TRAJ_THRESH = -7.5
HIGHER_IN_GMP_L_THAN_ERYP_PRESERVING_MEBEMP_ERYP_TRAJ_THRESH = -8.2

# preserving CLP_NKTDP traj
HIGHER_IN_CLP_AND_NKTDP_THAN_MPP_PRESERVING_CLP_NKTDP_TRAJ_THRESH = -7.6
HIGHER_IN_BEMP_THAN_CLP_AND_NKTDP_PRESERVING_CLP_NKTDP_TRAJ_THRESH = -7.5
HIGHER_IN_PRE_B_THAN_CLP_AND_NKTDP_PRESERVING_CLP_NKTDP_TRAJ_THRESH = -6.3

# preserving CLP_pro_B traj
HIGHER_IN_CLP_AND_PRO_B_THAN_MPP_PRESERVING_CLP_PRO_B_TRAJ_THRESH = -7
HIGHER_IN_NKTDP_THAN_CLP_AND_PRO_B_PRESERVING_CLP_PRO_B_TRAJ_THRESH = -7.7

print('pb_cd34_c_score_threshs was loaded/reloaded')

